CREATE DATABASE wenda;
USE wenda;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
`user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(64) NOT NULL,
`password` VARCHAR(120) NOT NULL,
`salt` VARCHAR(32) NOT NULL,
`head_url` VARCHAR(256) NOT NULL,
PRIMARY KEY (user_id),
UNIQUE KEY `name`(`name`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `question`;
CREATE TABLE `question` (
`question_id` INT NOT NULL AUTO_INCREMENT,
`title` VARCHAR(255) NOT NULL,
`content` TEXT NULL,
`user_id` INT NOT NULL,
`created_date` DATETIME NOT NULL,
`comment_count` INT NOT NULL,
PRIMARY KEY (`question_id`),
INDEX `date_index` (`created_date` ASC)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;